version: 2
jobs:
  build:
    docker:
      - image: rust
    environment:
      - NIGHTLY: nightly-2017-10-31
      - RUSTFLAGS: -C link-dead-code
    parallelism: 3
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-
      - run:
          name: Test
          command: scripts/test.sh
      - save_cache:
          key: cache-{{ epoch }}
          paths:
            - /usr/local/cargo
