version: 2
jobs:
  build:
    docker:
      - image: rust
    environment:
      - NIGHTLY: nightly
    parallelism: 3
    steps:
      - checkout
      - run:
          name: Test
          command: ./scripts/test.sh
