attributes_on_same_line_as_field = false
attributes_on_same_line_as_variant = false
max_width = 90
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
use_try_shorthand = true
